### ISSUE TITLE
Close the milestone and make release

### ISSUE THREAD

**Issue by mpostol** [mpostol/ASMD#119]
## Release ToDo List

- [x] Remove all not crucial tasks from the current milestone to a new one or backlog
- [x] Draft a new release
- [x] Update version information
- [x] Update ReleaseNotes.md and print it to .html using VC
- [x] Build the Release Configuration of the solution and perform functional tests
- [x] Create the installation package and publish in on the Release page
- [x] Update the Release page
- [x] Publish the release
- [ ] Close this issue and the parent milestone

> Note: after publication prepare and publish news to advertise the results

## Creating a self-extracting file

The comment below contains SFX script commands for RAR

```txt

Path=.\ASMD
Setup=Release\CAS.UA.ModelDesigner.exe installic
Title=Address Space Model Designer
Shortcut=D, Release\CAS.UA.ModelDesigner.exe,  , "OPC UA Address Space Model Designer", asmd, Release\OPC_UA_ASMD_48.ico

```

**Comment by mpostol** [comment]
It duplicated #115 and #112

**Comment by mpostol** [comment]
Add new release information to README.md
