### ISSUE TITLE
Remove dependency on CodeProtect - consolidated

### ISSUE THREAD

**Issue by mpostol** [mpostol/ASMD#211]
## Scope

- [ ] `ModelDesigner.DesignStudio` - run OPC DA Viewer in separate process (add appropriate .dll's to OPCViewer plugin folder (forked from #206)
- [ ] Remove CAS.Lib.CodeProtect.LibInstaller.InstallLicense (harmonize with previous)
- [ ] Remove reference to `AdvancedDelimitedListTraceListener` in the app.config (fork from #200)
- [ ] Remove CAS.Lib.CodeProtect.AssemblyHelper form `ASMD\ModelDesigner.DesignStudio\Properties\AssemblyInfo.cs`
- [ ] ModelDesigner.ImportExport: `ImportOPCDAAddressSpace` (class OPCDA) - copy functionality (AddressSpace) from the OPC VIewer stuff (guaranty compatybility on the xml file format) (forked from #206)
- [ ] ModelDesigner.ImportExport:: Remove references to package `CAS.CommServer.DA.Viewer` and all it depends on (forked from #206)
