### ISSUE TITLE
IEC61850 - documentation

### ISSUE THREAD

**Issue by mpostol** [mpostol/ASMD#264]
## Describe the bug

1. The solution has not been created. 
2. There is an exception thrown while creating the solution
3. The online documentation has not been generated
4. The MS Word documentation has not been generated

## Expected behavior

Fix all problems related to mage the model mentioned in the title.

## Tasks to be accomplished

- [x] work on independent branch
  - [x] create the branch
  - [x] update the software version
  - [x] updated the NuGet packages
  - [x] merge modifications to master
- [x] create solution for IEC61850 (consider models dependence)
- [x] online documentation
  - [x] create the documentation
  - [x] integrate the online documentation with the documentation published on mpostol/UA-Nodeset (interconnect issues)
- [x] create `docx` documentation

**Comment by mpostol** [comment]
Contributes to mpostol/UA-Nodeset#110
