### ISSUE TITLE
Release new version:  release  4.0.0-Alpha

### ISSUE THREAD

**Issue by mpostol** [mpostol/ASMD#48]
## Subtasks: 

- [x] Update version information for all published assemblies, 
- [x] Update and publish the code help documentation - update WIKI
- [x] Update Readme files
- [x] Create release front page
   - [x] Getting Started
   - [x] Version information
- [ ] Publish release
- [ ] Update the repository front page
