### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by mpostol** [mpostol/ASMD#60]
# Tasks
 
- [x] Running the tests #59
- [x] Update version information for all published assemblies (Model.t4), #69
- [x] Prepare an example if applicable #49
- [x] Update Readme files #36 
- [x] Create release front page #70 
- [x] Publish release
- [x] Update the repository front page
